development:
  bucket: acmeca-cedar-development
  access_key_id: AKIAJRDXDNBYM2AU4AJA
  secret_access_key: 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

test:
  bucket: acmeca-cedar-test
  access_key_id: AKIAJRDXDNBYM2AU4AJA
  secret_access_key: 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 

production:
  bucket: acmeca-cedar-production
  access_key_id: AKIAJRDXDNBYM2AU4AJA
  secret_access_key: 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 
